# Site settings
title: There4
author: Craig Davis
brand_domain: THERE4.IO
brand_symbol: "∴"
home_heading: "Software, machines, making, bikes, and other things learned by doing."
header-img: img/headers/mountain-dog.jpg
email: cadavis@gmail.com
description: "Field notes from Craig Davis about software, machines, making, bikes, books, and life."
baseurl: ""
url: "https://there4.io"
twitter_username: There4Dev
github_username:  craig-davis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: 
  - bin
  - docs
  - less
  - node_modules
  - scripts
  - test
  - Gruntfile.js
  - package.json
  - README.md
  - post.rb
  - tmp/
  - vendor/
  - Gemfile
  - Gemfile.lock

plugins:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-gist
