# Site settings
title: Craig Davis
header-img: img/headers/mountain-dog.jpg
email: cadavis@gmail.com
description: "Craig Davis - Code, Bikes, Photos"
baseurl: ""
url: "https://there4.io"
twitter_username: There4Dev
github_username:  craig-davis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "post.rb"]

gems:
- jekyll-redirect-from
- jekyll-paginate
- jekyll-gist
